In [1]:
import pandas as pd
import os
import matplotlib.pyplot as plt
import seaborn as sns

In [ ]:
caminho_dos_arquivos = 'C:\\Users\\FIC\\Documents\\Rafael-Dias-Python\\desafio-super-atacadista\\vendas\\'

In [ ]:
arquivos = []

In [ ]:
for arquivo in os.listdir(caminho_dos_arquivos):
    arquivos.append(caminho_dos_arquivos + arquivo)
arquivos

['C:\\Users\\FIC\\Documents\\Rafael-Dias-Python\\desafio-super-atacadista\\vendas\\Vendas 2017.xlsx',
 'C:\\Users\\FIC\\Documents\\Rafael-Dias-Python\\desafio-super-atacadista\\vendas\\Vendas 2018.xlsx',
 'C:\\Users\\FIC\\Documents\\Rafael-Dias-Python\\desafio-super-atacadista\\vendas\\Vendas 2019.xlsx',
 'C:\\Users\\FIC\\Documents\\Rafael-Dias-Python\\desafio-super-atacadista\\vendas\\Vendas 2020.xlsx',
 'C:\\Users\\FIC\\Documents\\Rafael-Dias-Python\\desafio-super-atacadista\\vendas\\Vendas 2021.xlsx',
 'C:\\Users\\FIC\\Documents\\Rafael-Dias-Python\\desafio-super-atacadista\\vendas\\Vendas 2022.xlsx']

In [ ]:
vendas = pd.DataFrame()

In [ ]:
for arquivo in arquivos:
    df = pd.read_excel(arquivo, sheet_name='Vendas')
    vendas = pd.concat([df, vendas])

In [ ]:
vendas.info()

<class 'pandas.core.frame.DataFrame'>
Index: 302840 entries, 0 to 91593
Data columns (total 9 columns):
 #   Column          Non-Null Count   Dtype
---  ------          --------------   -----
 0   DataEmissao     302840 non-null  datetime64[ns]
 1   DataVencimento  302840 non-null  datetime64[ns]
 2   NFe             302840 non-null  int64
 3   cdCliente       302840 non-null  int64
 4   cdVendedor      302840 non-null  int64
 5   cdProduto       302840 non-null  int64
 6   QtdItens        302840 non-null  int64
 7   ValorUnitario   302840 non-null  float64
 8   Peso Líquido    302840 non-null  float64
dtypes: datetime64[ns](2), float64(2), int64(5)
memory usage: 23.1 MB

In [ ]:
vendas.head()

,DataEmissao,DataVencimento,NFe,cdCliente,cdVendedor,cdProduto,QtdItens,ValorUnitario,Peso Líquido
0,2022-01-01,2022-02-01,2123073,3785072,285,1154,6,3.25,0.30
1,2022-01-01,2022-02-08,2149604,3799504,326,1154,6,3.25,0.30
2,2022-01-01,2022-02-09,2173654,2957188,326,1154,6,3.20,0.30
3,2022-01-01,2022-01-21,2113210,3854414,326,1154,6,3.33,0.30
4,2022-01-01,2022-01-28,2156463,2950203,102,1154,6,2.62,1.38

In [ ]:
caminho = 'C:\\Users\\FIC\\Documents\\Rafael-Dias-Python\\desafio-super-atacadista\\'
arquivo = 'Dimensões.xlsx'

cliente = pd.read_excel(caminho + arquivo, sheet_name='Cliente')
produto = pd.read_excel(caminho + arquivo, sheet_name='Produto')
grupo_produto = pd.read_excel(caminho + arquivo, sheet_name='GrupoProduto')
vendedor = pd.read_excel(caminho + arquivo, sheet_name='Vendedor')
data = pd.read_excel(caminho + arquivo, sheet_name='Data')

In [ ]:
cliente.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1411 entries, 0 to 1410
Data columns (total 6 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   cdCliente     1411 non-null   int64
 1   Razão Social  1411 non-null   object
 2   Status        1411 non-null   object
 3   Categoria     1411 non-null   object
 4   Cidade        1411 non-null   object
 5   UF            1411 non-null   object
dtypes: int64(1), object(5)
memory usage: 66.3+ KB

In [ ]:
produto.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 2736 entries, 0 to 2735
Data columns (total 3 columns):
 #   Column     Non-Null Count  Dtype
---  ------     --------------  -----
 0   cdProduto  2736 non-null   int64
 1   Descrição  2736 non-null   object
 2   cdGrupo    2736 non-null   int64
dtypes: int64(2), object(1)
memory usage: 64.2+ KB

In [ ]:
grupo_produto.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 36 entries, 0 to 35
Data columns (total 3 columns):
 #   Column   Non-Null Count  Dtype
---  ------   --------------  -----
 0   cdGrupo  36 non-null     int64
 1   Grupo    36 non-null     object
 2   Linha    36 non-null     object
dtypes: int64(1), object(2)
memory usage: 992.0+ bytes

In [ ]:
vendedor.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 12 entries, 0 to 11
Data columns (total 7 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   cdVendedor    12 non-null     int64
 1   Vendedor      12 non-null     object
 2   cdSupervisor  12 non-null     int64
 3   Supervisor    12 non-null     object
 4   cdGerente     12 non-null     int64
 5   Gerente       12 non-null     object
 6   Equipe        12 non-null     object
dtypes: int64(3), object(4)
memory usage: 800.0+ bytes

In [ ]:
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 2191 entries, 0 to 2190
Data columns (total 5 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   Data    2191 non-null   datetime64[ns]
 1   Ano     2191 non-null   int64
 2   Mes     2191 non-null   object
 3   MesNum  2191 non-null   int64
 4   Dia     2191 non-null   int64
dtypes: datetime64[ns](1), int64(3), object(1)
memory usage: 85.7+ KB

In [92]:
caminho = 'C:\\Users\\FIC\\Documents\\Rafael-Dias-Python\\desafio-super-atacadista\\'
arquivo = 'Metas.xlsx'
meta = pd.read_excel(caminho + arquivo, sheet_name='Metas')

In [93]:
meta.head()

,Unnamed: 0,Metas por Vendedor,Unnamed: 2,Unnamed: 3,Unnamed: 4,Unnamed: 5,Unnamed: 6,Unnamed: 7,Unnamed: 8,Unnamed: 9,...,Unnamed: 64,Unnamed: 65,Unnamed: 66,Unnamed: 67,Unnamed: 68,Unnamed: 69,Unnamed: 70,Unnamed: 71,Unnamed: 72,Unnamed: 73
0,NaN,Última Atualização: 31/12/2019,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,NaN,cdVendedor,2017-01-01 00:00:00,2017-02-01 00:00:00,2017-03-01 00:00:00,2017-04-01 00:00:00,2017-05-01 00:00:00,2017-06-01 00:00:00,2017-07-01 00:00:00,2017-08-01 00:00:00,...,2022-03-01 00:00:00,2022-04-01 00:00:00,2022-05-01 00:00:00,2022-06-01 00:00:00,2022-07-01 00:00:00,2022-08-01 00:00:00,2022-09-01 00:00:00,2022-10-01 00:00:00,2022-11-01 00:00:00,2022-12-01 00:00:00
4,NaN,102,140768.312981,124258.753484,169509.931262,143465.231352,98423.627768,133401.861987,109124.992168,221597.228027,...,98801,72820,62828,23732,59726,72648,90886,33627,22575,147200

In [94]:
meta = meta.iloc[3:,1:]

In [95]:
meta.head()

,Metas por Vendedor,Unnamed: 2,Unnamed: 3,Unnamed: 4,Unnamed: 5,Unnamed: 6,Unnamed: 7,Unnamed: 8,Unnamed: 9,Unnamed: 10,...,Unnamed: 64,Unnamed: 65,Unnamed: 66,Unnamed: 67,Unnamed: 68,Unnamed: 69,Unnamed: 70,Unnamed: 71,Unnamed: 72,Unnamed: 73
3,cdVendedor,2017-01-01 00:00:00,2017-02-01 00:00:00,2017-03-01 00:00:00,2017-04-01 00:00:00,2017-05-01 00:00:00,2017-06-01 00:00:00,2017-07-01 00:00:00,2017-08-01 00:00:00,2017-09-01 00:00:00,...,2022-03-01 00:00:00,2022-04-01 00:00:00,2022-05-01 00:00:00,2022-06-01 00:00:00,2022-07-01 00:00:00,2022-08-01 00:00:00,2022-09-01 00:00:00,2022-10-01 00:00:00,2022-11-01 00:00:00,2022-12-01 00:00:00
4,102,140768.312981,124258.753484,169509.931262,143465.231352,98423.627768,133401.861987,109124.992168,221597.228027,101603.974771,...,98801,72820,62828,23732,59726,72648,90886,33627,22575,147200
5,125,21525.584613,50778.518843,80286.310022,117769.05503,162043.205771,184889.338359,175629.570395,120097.495562,110607.719934,...,102588,111966,73820,63180,91574,147501,27211,35545,24405,95060
6,144,72301.437981,47360.51627,54145.357333,89457.661634,115437.266528,72356.845601,164689.100713,102330.724424,112396.578585,...,34363,84436,107508,122783,63397,91962,96559,86822,93434,21425
7,194,0,0,0,0,0,0,0,0,0,...,143281,145669,107315,121999,87128,51302,73211,49920,99219,82882

In [96]:
meta_lista = meta.head(1)

In [97]:
meta_lista

,Metas por Vendedor,Unnamed: 2,Unnamed: 3,Unnamed: 4,Unnamed: 5,Unnamed: 6,Unnamed: 7,Unnamed: 8,Unnamed: 9,Unnamed: 10,...,Unnamed: 64,Unnamed: 65,Unnamed: 66,Unnamed: 67,Unnamed: 68,Unnamed: 69,Unnamed: 70,Unnamed: 71,Unnamed: 72,Unnamed: 73
3,cdVendedor,2017-01-01 00:00:00,2017-02-01 00:00:00,2017-03-01 00:00:00,2017-04-01 00:00:00,2017-05-01 00:00:00,2017-06-01 00:00:00,2017-07-01 00:00:00,2017-08-01 00:00:00,2017-09-01 00:00:00,...,2022-03-01 00:00:00,2022-04-01 00:00:00,2022-05-01 00:00:00,2022-06-01 00:00:00,2022-07-01 00:00:00,2022-08-01 00:00:00,2022-09-01 00:00:00,2022-10-01 00:00:00,2022-11-01 00:00:00,2022-12-01 00:00:00

In [98]:
meta_lista.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1 entries, 3 to 3
Data columns (total 73 columns):
 #   Column              Non-Null Count  Dtype
---  ------              --------------  -----
 0   Metas por Vendedor  1 non-null      object
 1   Unnamed: 2          1 non-null      object
 2   Unnamed: 3          1 non-null      object
 3   Unnamed: 4          1 non-null      object
 4   Unnamed: 5          1 non-null      object
 5   Unnamed: 6          1 non-null      object
 6   Unnamed: 7          1 non-null      object
 7   Unnamed: 8          1 non-null      object
 8   Unnamed: 9          1 non-null      object
 9   Unnamed: 10         1 non-null      object
 10  Unnamed: 11         1 non-null      object
 11  Unnamed: 12         1 non-null      object
 12  Unnamed: 13         1 non-null      object
 13  Unnamed: 14         1 non-null      object
 14  Unnamed: 15         1 non-null      object
 15  Unnamed: 16         1 non-null      object
 16  Unnamed: 17         1 non-null      object
 17  Unnamed: 18         1 non-null      object
 18  Unnamed: 19         1 non-null      object
 19  Unnamed: 20         1 non-null      object
 20  Unnamed: 21         1 non-null      object
 21  Unnamed: 22         1 non-null      object
 22  Unnamed: 23         1 non-null      object
 23  Unnamed: 24         1 non-null      object
 24  Unnamed: 25         1 non-null      object
 25  Unnamed: 26         1 non-null      object
 26  Unnamed: 27         1 non-null      object
 27  Unnamed: 28         1 non-null      object
 28  Unnamed: 29         1 non-null      object
 29  Unnamed: 30         1 non-null      object
 30  Unnamed: 31         1 non-null      object
 31  Unnamed: 32         1 non-null      object
 32  Unnamed: 33         1 non-null      object
 33  Unnamed: 34         1 non-null      object
 34  Unnamed: 35         1 non-null      object
 35  Unnamed: 36         1 non-null      object
 36  Unnamed: 37         1 non-null      object
 37  Unnamed: 38         1 non-null      object
 38  Unnamed: 39         1 non-null      object
 39  Unnamed: 40         1 non-null      object
 40  Unnamed: 41         1 non-null      object
 41  Unnamed: 42         1 non-null      object
 42  Unnamed: 43         1 non-null      object
 43  Unnamed: 44         1 non-null      object
 44  Unnamed: 45         1 non-null      object
 45  Unnamed: 46         1 non-null      object
 46  Unnamed: 47         1 non-null      object
 47  Unnamed: 48         1 non-null      object
 48  Unnamed: 49         1 non-null      object
 49  Unnamed: 50         1 non-null      object
 50  Unnamed: 51         1 non-null      object
 51  Unnamed: 52         1 non-null      object
 52  Unnamed: 53         1 non-null      object
 53  Unnamed: 54         1 non-null      object
 54  Unnamed: 55         1 non-null      object
 55  Unnamed: 56         1 non-null      object
 56  Unnamed: 57         1 non-null      object
 57  Unnamed: 58         1 non-null      object
 58  Unnamed: 59         1 non-null      object
 59  Unnamed: 60         1 non-null      object
 60  Unnamed: 61         1 non-null      object
 61  Unnamed: 62         1 non-null      object
 62  Unnamed: 63         1 non-null      object
 63  Unnamed: 64         1 non-null      object
 64  Unnamed: 65         1 non-null      object
 65  Unnamed: 66         1 non-null      object
 66  Unnamed: 67         1 non-null      object
 67  Unnamed: 68         1 non-null      object
 68  Unnamed: 69         1 non-null      object
 69  Unnamed: 70         1 non-null      object
 70  Unnamed: 71         1 non-null      object
 71  Unnamed: 72         1 non-null      object
 72  Unnamed: 73         1 non-null      object
dtypes: object(73)
memory usage: 716.0+ bytes

In [99]:
lista = meta_lista.values.tolist()

In [100]:
lista = lista[0]

In [101]:
type(lista)

list

In [102]:
len(lista)

73

In [103]:
meta.columns = [lista]

In [104]:
meta.head()

,cdVendedor,2017-01-01 00:00:00,2017-02-01 00:00:00,2017-03-01 00:00:00,2017-04-01 00:00:00,2017-05-01 00:00:00,2017-06-01 00:00:00,2017-07-01 00:00:00,2017-08-01 00:00:00,2017-09-01 00:00:00,...,2022-03-01 00:00:00,2022-04-01 00:00:00,2022-05-01 00:00:00,2022-06-01 00:00:00,2022-07-01 00:00:00,2022-08-01 00:00:00,2022-09-01 00:00:00,2022-10-01 00:00:00,2022-11-01 00:00:00,2022-12-01 00:00:00
3,cdVendedor,2017-01-01 00:00:00,2017-02-01 00:00:00,2017-03-01 00:00:00,2017-04-01 00:00:00,2017-05-01 00:00:00,2017-06-01 00:00:00,2017-07-01 00:00:00,2017-08-01 00:00:00,2017-09-01 00:00:00,...,2022-03-01 00:00:00,2022-04-01 00:00:00,2022-05-01 00:00:00,2022-06-01 00:00:00,2022-07-01 00:00:00,2022-08-01 00:00:00,2022-09-01 00:00:00,2022-10-01 00:00:00,2022-11-01 00:00:00,2022-12-01 00:00:00
4,102,140768.312981,124258.753484,169509.931262,143465.231352,98423.627768,133401.861987,109124.992168,221597.228027,101603.974771,...,98801,72820,62828,23732,59726,72648,90886,33627,22575,147200
5,125,21525.584613,50778.518843,80286.310022,117769.05503,162043.205771,184889.338359,175629.570395,120097.495562,110607.719934,...,102588,111966,73820,63180,91574,147501,27211,35545,24405,95060
6,144,72301.437981,47360.51627,54145.357333,89457.661634,115437.266528,72356.845601,164689.100713,102330.724424,112396.578585,...,34363,84436,107508,122783,63397,91962,96559,86822,93434,21425
7,194,0,0,0,0,0,0,0,0,0,...,143281,145669,107315,121999,87128,51302,73211,49920,99219,82882

In [105]:
meta = meta.iloc[1:,:]

In [106]:
meta.head()

,cdVendedor,2017-01-01 00:00:00,2017-02-01 00:00:00,2017-03-01 00:00:00,2017-04-01 00:00:00,2017-05-01 00:00:00,2017-06-01 00:00:00,2017-07-01 00:00:00,2017-08-01 00:00:00,2017-09-01 00:00:00,...,2022-03-01 00:00:00,2022-04-01 00:00:00,2022-05-01 00:00:00,2022-06-01 00:00:00,2022-07-01 00:00:00,2022-08-01 00:00:00,2022-09-01 00:00:00,2022-10-01 00:00:00,2022-11-01 00:00:00,2022-12-01 00:00:00
4,102,140768.312981,124258.753484,169509.931262,143465.231352,98423.627768,133401.861987,109124.992168,221597.228027,101603.974771,...,98801,72820,62828,23732,59726,72648,90886,33627,22575,147200
5,125,21525.584613,50778.518843,80286.310022,117769.05503,162043.205771,184889.338359,175629.570395,120097.495562,110607.719934,...,102588,111966,73820,63180,91574,147501,27211,35545,24405,95060
6,144,72301.437981,47360.51627,54145.357333,89457.661634,115437.266528,72356.845601,164689.100713,102330.724424,112396.578585,...,34363,84436,107508,122783,63397,91962,96559,86822,93434,21425
7,194,0,0,0,0,0,0,0,0,0,...,143281,145669,107315,121999,87128,51302,73211,49920,99219,82882
8,196,75253.91149,56094.071733,156709.108284,82723.073158,47426.320283,66398.220086,91840.461612,136680.893152,87425.550099,...,121938,29782,100255,113866,116867,135246,88283,81605,20216,107324

In [107]:
meta = meta.transpose()

In [108]:
meta.head()

,4,5,6,7,8,9,10,11,12,13,14
cdVendedor,102,125,144,194,196,215,265,285,326,660,669
2017-01-01 00:00:00,140768.312981,21525.584613,72301.437981,0,75253.91149,286012.89817,122199.726847,0,0,0,0
2017-02-01 00:00:00,124258.753484,50778.518843,47360.51627,0,56094.071733,268739.946775,147007.556793,0,0,0,0
2017-03-01 00:00:00,169509.931262,80286.310022,54145.357333,0,156709.108284,329813.357769,127262.128128,0,0,0,0
2017-04-01 00:00:00,143465.231352,117769.05503,89457.661634,0,82723.073158,159143.4362,206980.493152,0,0,0,0

In [109]:
meta = meta.rename_axis('Index').reset_index()

In [110]:
meta.head()

,Index,4,5,6,7,8,9,10,11,12,13,14
0,cdVendedor,102,125,144,194,196,215,265,285,326,660,669
1,2017-01-01 00:00:00,140768.312981,21525.584613,72301.437981,0,75253.91149,286012.89817,122199.726847,0,0,0,0
2,2017-02-01 00:00:00,124258.753484,50778.518843,47360.51627,0,56094.071733,268739.946775,147007.556793,0,0,0,0
3,2017-03-01 00:00:00,169509.931262,80286.310022,54145.357333,0,156709.108284,329813.357769,127262.128128,0,0,0,0
4,2017-04-01 00:00:00,143465.231352,117769.05503,89457.661634,0,82723.073158,159143.4362,206980.493152,0,0,0,0

In [111]:
meta_lista = meta.head(1)

In [112]:
meta_lista

        Index    4    5    6    7    8    9   10   11   12   13   14
0  cdVendedor  102  125  144  194  196  215  265  285  326  660  669

In [113]:
meta_lista.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1 entries, 0 to 0
Data columns (total 12 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   Index   1 non-null      object
 1   4       1 non-null      object
 2   5       1 non-null      object
 3   6       1 non-null      object
 4   7       1 non-null      object
 5   8       1 non-null      object
 6   9       1 non-null      object
 7   10      1 non-null      object
 8   11      1 non-null      object
 9   12      1 non-null      object
 10  13      1 non-null      object
 11  14      1 non-null      object
dtypes: object(12)
memory usage: 224.0+ bytes

In [114]:
lista_2 = meta_lista.values.tolist()

In [115]:
lista_2

[['cdVendedor', 102, 125, 144, 194, 196, 215, 265, 285, 326, 660, 669]]

In [116]:
lista_2 = lista_2[0]

In [117]:
len(lista_2)

12

In [118]:
meta.columns = [lista_2]

In [119]:
meta.head()

,cdVendedor,102,125,144,194,196,215,265,285,326,660,669
0,cdVendedor,102,125,144,194,196,215,265,285,326,660,669
1,2017-01-01 00:00:00,140768.312981,21525.584613,72301.437981,0,75253.91149,286012.89817,122199.726847,0,0,0,0
2,2017-02-01 00:00:00,124258.753484,50778.518843,47360.51627,0,56094.071733,268739.946775,147007.556793,0,0,0,0
3,2017-03-01 00:00:00,169509.931262,80286.310022,54145.357333,0,156709.108284,329813.357769,127262.128128,0,0,0,0
4,2017-04-01 00:00:00,143465.231352,117769.05503,89457.661634,0,82723.073158,159143.4362,206980.493152,0,0,0,0

In [120]:
meta.rename(columns = {'cdVendedor':'DataVenda'}, inplace = True)

In [121]:
meta.head()

,DataVenda,102,125,144,194,196,215,265,285,326,660,669
0,cdVendedor,102,125,144,194,196,215,265,285,326,660,669
1,2017-01-01 00:00:00,140768.312981,21525.584613,72301.437981,0,75253.91149,286012.89817,122199.726847,0,0,0,0
2,2017-02-01 00:00:00,124258.753484,50778.518843,47360.51627,0,56094.071733,268739.946775,147007.556793,0,0,0,0
3,2017-03-01 00:00:00,169509.931262,80286.310022,54145.357333,0,156709.108284,329813.357769,127262.128128,0,0,0,0
4,2017-04-01 00:00:00,143465.231352,117769.05503,89457.661634,0,82723.073158,159143.4362,206980.493152,0,0,0,0

In [122]:
meta = meta.iloc[1:,:]

In [153]:
meta.head()

,DataVenda,102,125,144,194,196,215,265,285,326,660,669
1,2017-01-01 00:00:00,140768.312981,21525.584613,72301.437981,0,75253.91149,286012.89817,122199.726847,0,0,0,0
2,2017-02-01 00:00:00,124258.753484,50778.518843,47360.51627,0,56094.071733,268739.946775,147007.556793,0,0,0,0
3,2017-03-01 00:00:00,169509.931262,80286.310022,54145.357333,0,156709.108284,329813.357769,127262.128128,0,0,0,0
4,2017-04-01 00:00:00,143465.231352,117769.05503,89457.661634,0,82723.073158,159143.4362,206980.493152,0,0,0,0
5,2017-05-01 00:00:00,98423.627768,162043.205771,115437.266528,0,47426.320283,117572.134697,119509.500049,0,0,0,0

In [152]:
meta.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 72 entries, 1 to 72
Data columns (total 12 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   (DataVenda,)  72 non-null     object
 1   (102,)        72 non-null     object
 2   (125,)        72 non-null     object
 3   (144,)        72 non-null     object
 4   (194,)        72 non-null     object
 5   (196,)        72 non-null     object
 6   (215,)        72 non-null     object
 7   (265,)        72 non-null     object
 8   (285,)        72 non-null     object
 9   (326,)        72 non-null     object
 10  (660,)        72 non-null     object
 11  (669,)        72 non-null     object
dtypes: object(12)
memory usage: 6.9+ KB

In [154]:
meta.reset_index(inplace=True)
meta= meta.iloc[:,1:]

In [155]:
meta.head()

,DataVenda,102,125,144,194,196,215,265,285,326,660,669
0,2017-01-01 00:00:00,140768.312981,21525.584613,72301.437981,0,75253.91149,286012.89817,122199.726847,0,0,0,0
1,2017-02-01 00:00:00,124258.753484,50778.518843,47360.51627,0,56094.071733,268739.946775,147007.556793,0,0,0,0
2,2017-03-01 00:00:00,169509.931262,80286.310022,54145.357333,0,156709.108284,329813.357769,127262.128128,0,0,0,0
3,2017-04-01 00:00:00,143465.231352,117769.05503,89457.661634,0,82723.073158,159143.4362,206980.493152,0,0,0,0
4,2017-05-01 00:00:00,98423.627768,162043.205771,115437.266528,0,47426.320283,117572.134697,119509.500049,0,0,0,0